root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app.exe"
  bin = "tmp/app.exe"
  full_bin = "tmp/app.exe"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true
